/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import employeemanager.Employee;
import employeemanager.EmployeeSaving;
import employeemanager.UsernameLedger;

/**
 *
 * @author Ralty
 */
public class AdminAddEmployee extends javax.swing.JFrame {

    private int accountType = 0;
    private int gender = 0;
    AdminHomePage page;

    public AdminAddEmployee() {
        initComponents();
        
    }
    
    public AdminAddEmployee(AdminHomePage a, int x, int y) {
        initComponents();
        this.setLocation(x, y);
        this.setResizable(false); // Make the frame not resizable
        this.page = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        AccountTypeLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        idInputField = new javax.swing.JTextField();
        ageInputField = new javax.swing.JTextField();
        positionInputField = new javax.swing.JTextField();
        salaryInputField = new javax.swing.JTextField();
        userTypeCombo = new javax.swing.JComboBox<>();
        genderCombo = new javax.swing.JComboBox<>();
        addEmployeeButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee-addition-label.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        idLabel.setForeground(new java.awt.Color(39, 39, 39));
        idLabel.setText("ID:");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(39, 39, 39));
        nameLabel.setText("Name:");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(39, 39, 39));
        ageLabel.setText("Age:");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(39, 39, 39));
        genderLabel.setText("Gender:");

        AccountTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        AccountTypeLabel.setForeground(new java.awt.Color(39, 39, 39));
        AccountTypeLabel.setText("User Type:");

        positionLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(39, 39, 39));
        positionLabel.setText("Position:");

        salaryLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(39, 39, 39));
        salaryLabel.setText("Salary:");

        nameInputField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });

        idInputField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        idInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputFieldActionPerformed(evt);
            }
        });

        ageInputField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ageInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageInputFieldActionPerformed(evt);
            }
        });

        positionInputField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        positionInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionInputFieldActionPerformed(evt);
            }
        });

        salaryInputField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        salaryInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryInputFieldActionPerformed(evt);
            }
        });

        userTypeCombo.setBackground(new java.awt.Color(153, 153, 153));
        userTypeCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTypeCombo.setForeground(new java.awt.Color(204, 204, 204));
        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "TBA" }));
        userTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeComboActionPerformed(evt);
            }
        });

        genderCombo.setBackground(new java.awt.Color(153, 153, 153));
        genderCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderCombo.setForeground(new java.awt.Color(204, 204, 204));
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(138, 138, 138)
                        .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryLabel)
                            .addComponent(positionLabel)
                            .addComponent(AccountTypeLabel)
                            .addComponent(genderLabel)
                            .addComponent(ageLabel)
                            .addComponent(idLabel))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salaryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idInputField))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageInputField))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLabel)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccountTypeLabel)
                    .addComponent(userTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(positionInputField))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(salaryInputField))
                .addGap(55, 55, 55))
        );

        addEmployeeButton.setBackground(new java.awt.Color(29, 151, 29));
        addEmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(51, 51, 51));
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.png"))); // NOI18N
        BackButton.setContentAreaFilled(false);
        BackButton.setSelected(true);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(313, 313, 313))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    private void idInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputFieldActionPerformed

    private void ageInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageInputFieldActionPerformed

    private void positionInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionInputFieldActionPerformed

    private void salaryInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryInputFieldActionPerformed

    private void userTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeComboActionPerformed
        String accountTypeValue = (String) genderCombo.getSelectedItem();

        if (accountTypeValue.equals("Employee")) {
            accountType = 0;
        } else if (accountTypeValue.equals("TBA")) {
            accountType = 0;
        }
    }//GEN-LAST:event_userTypeComboActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // (String name, int id, int age, int gender, String position, int salary
        String name = this.nameInputField.getText().trim();
        String idString = this.idInputField.getText().trim();
        String ageString = this.ageInputField.getText().trim();
        String salaryString = this.salaryInputField.getText().trim();
        String position = this.positionInputField.getText().trim();

        int flag = 0;

        //checks if name input is empty
        if (name.equals("")) {
            showError("Name can't be empty");
            flag = 1;
            return;
        }

        //checks if ID input is empty
        if (idString.equals("")) {
            showError("ID can't be empty");
            flag = 1;
            return;
        }

        //checks if age input is empty
        if (ageString.equals("")) {
            showError("Age can't be empty");
            flag = 1;
            return;
        }

        //checks if position input is empty
        if (position.equals("")) {
            showError("Position can't be empty");
            flag = 1;
            return;
        }
        
        //checks if salary input is empty
        if (salaryString.equals("")) {
            showError("Salary can't be empty");
            flag = 1;
            return;
        }

        //checks if id input has non int value
        int id;
        try {
            id = Integer.parseInt(idString);
        } catch (NumberFormatException e) {
            showError("ID must be a number");
            flag = 1;
            return;
        }

        //checks if age input has non int value
        int age;
        try {
            age = Integer.parseInt(ageString);
        } catch (NumberFormatException e) {
            showError("Age must be a number");
            flag = 1;
            return;
        }

        //checks if salary input has non int value
        int salary;
        try {
            salary = Integer.parseInt(salaryString);
        } catch (NumberFormatException e) {
            showError("Salary must be a valid number");
            flag = 1;
            return;
        }

        // If everything is okay, initialize Employee object
        if (flag == 0) {
            //set button text back to normal
            addEmployeeButton.setBackground(new java.awt.Color(29, 151, 29));
            addEmployeeButton.setText("Employee Added");
            
            
            Employee e = new Employee(name, id, age, gender, position, salary);
            System.out.println(e.getName() + e.getId() + e.getGender() + e.getPosition() + e.getSalary() + e.getUsername() + e.getPassword() + e.getIsAdmin());
            
            EmployeeSaving employeeSave = new EmployeeSaving(e);
            UsernameLedger usernameSave = new UsernameLedger(e);
            employeeSave.saveToFile();
            usernameSave.saveToFile();
        }
        


    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    //Shows error message in Add Employee button
    private void showError(String message) {
        addEmployeeButton.setText(message);
        addEmployeeButton.setBackground(new java.awt.Color(206, 35, 35));
    }

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        String genderValue = (String) genderCombo.getSelectedItem();

        if (genderValue.equals("Male")) {
            gender = 0;
        } else if (genderValue.equals("Female")) {
            gender = 1;
        }
    }//GEN-LAST:event_genderComboActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        page.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JTextField ageInputField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField idInputField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField positionInputField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField salaryInputField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JComboBox<String> userTypeCombo;
    // End of variables declaration//GEN-END:variables
}
