package GUI;

import employeemanager.TaskSaving;
import employeemanager.UserNotFoundException;

/**
 *
 * @author Rafee-M
 */
public class AdminTaskAssignment extends javax.swing.JFrame {

    private String username;
    private TaskSaving taskSaving;
    
    public AdminTaskAssignment() {
        initComponents();
        taskSaving = new TaskSaving();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminTaskAssignPanel = new javax.swing.JPanel();
        AdminTaskAssignLogo = new javax.swing.JLabel();
        EmployeeNameLabel = new javax.swing.JLabel();
        EmployeeNameLabel1 = new javax.swing.JLabel();
        EmployeeUsernameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskDetailArea = new javax.swing.JTextArea();
        ShowUsernameButton = new javax.swing.JButton();
        AssignTaskButton = new javax.swing.JButton();
        EmployeeErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminTaskAssignPanel.setBackground(new java.awt.Color(51, 51, 51));
        AdminTaskAssignPanel.setForeground(new java.awt.Color(51, 51, 51));

        AdminTaskAssignLogo.setBackground(new java.awt.Color(203, 78, 22));
        AdminTaskAssignLogo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        AdminTaskAssignLogo.setForeground(new java.awt.Color(228, 228, 228));
        AdminTaskAssignLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ralty\\Downloads\\Employee\\docs\\images\\task-assign-logo.png")); // NOI18N

        EmployeeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmployeeNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeNameLabel.setText("Enter Employee Username:");

        EmployeeNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmployeeNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeNameLabel1.setText("Enter Task Description:");

        EmployeeUsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmployeeUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeUsernameFieldActionPerformed(evt);
            }
        });

        TaskDetailArea.setColumns(20);
        TaskDetailArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TaskDetailArea.setRows(5);
        jScrollPane1.setViewportView(TaskDetailArea);

        ShowUsernameButton.setBackground(new java.awt.Color(102, 102, 102));
        ShowUsernameButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ShowUsernameButton.setText("Show Usernames");
        ShowUsernameButton.setFocusPainted(false);

        AssignTaskButton.setBackground(new java.awt.Color(102, 102, 102));
        AssignTaskButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AssignTaskButton.setForeground(new java.awt.Color(255, 255, 255));
        AssignTaskButton.setText("Assign");
        AssignTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTaskButtonActionPerformed(evt);
            }
        });

        EmployeeErrorLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EmployeeErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        EmployeeErrorLabel.setText("Employee Not Found!");
        EmployeeErrorLabel.setVisible(false);

        javax.swing.GroupLayout AdminTaskAssignPanelLayout = new javax.swing.GroupLayout(AdminTaskAssignPanel);
        AdminTaskAssignPanel.setLayout(AdminTaskAssignPanelLayout);
        AdminTaskAssignPanelLayout.setHorizontalGroup(
            AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                                .addComponent(EmployeeNameLabel)
                                .addGap(52, 52, 52)
                                .addComponent(EmployeeUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                                .addComponent(EmployeeNameLabel1)
                                .addGap(67, 67, 67)
                                .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeErrorLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ShowUsernameButton)
                        .addGap(268, 268, 268)
                        .addComponent(AssignTaskButton)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminTaskAssignPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AdminTaskAssignLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        AdminTaskAssignPanelLayout.setVerticalGroup(
            AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTaskAssignPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AdminTaskAssignLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNameLabel)
                    .addComponent(EmployeeUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeNameLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(EmployeeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AdminTaskAssignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminTaskAssignPanelLayout.createSequentialGroup()
                        .addComponent(ShowUsernameButton)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminTaskAssignPanelLayout.createSequentialGroup()
                        .addComponent(AssignTaskButton)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminTaskAssignPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminTaskAssignPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AssignTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignTaskButtonActionPerformed
        this.username = EmployeeUsernameField.getText();
        String taskDetails = TaskDetailArea.getText();
        
        try{
            taskSaving.assignTask(username, taskDetails);
            System.out.println("s");
            EmployeeErrorLabel.setForeground(new java.awt.Color(44, 200, 55));
            EmployeeErrorLabel.setText("Assigned Successfully");
            EmployeeErrorLabel.setVisible(true);
            
        }catch(UserNotFoundException e){
            
            EmployeeErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
            EmployeeErrorLabel.setText("Employee Not Found!");
            EmployeeErrorLabel.setVisible(true);
            
        }

        
        
    }//GEN-LAST:event_AssignTaskButtonActionPerformed

    private void EmployeeUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeUsernameFieldActionPerformed
        
        
    }//GEN-LAST:event_EmployeeUsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTaskAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTaskAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTaskAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTaskAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTaskAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminTaskAssignLogo;
    private javax.swing.JPanel AdminTaskAssignPanel;
    private javax.swing.JButton AssignTaskButton;
    private javax.swing.JLabel EmployeeErrorLabel;
    private javax.swing.JLabel EmployeeNameLabel;
    private javax.swing.JLabel EmployeeNameLabel1;
    private javax.swing.JTextField EmployeeUsernameField;
    private javax.swing.JButton ShowUsernameButton;
    private javax.swing.JTextArea TaskDetailArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
