package GUI;

import employeemanager.ComboBoxFill;
import employeemanager.Employee;
import employeemanager.EmployeeSaving;
import employeemanager.FileInfoReader;
import employeemanager.UserNotFoundException;
import employeemanager.UsernameLedger;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Rafee-M
 */
public class AdminEmployeeRemoval extends javax.swing.JFrame implements ComboBoxFill {

    private FileInfoReader infoReader = new FileInfoReader();
    private Employee employee;
    private AdminHomePage page;

    public AdminEmployeeRemoval() {

        initComponents();
        fillComboBox();
        Dimension panelSize = EmployeeInfoPanel.getSize();
        int width = panelSize.width;
        int height = panelSize.height;
        System.out.println("Width: " + width + ", Height: " + height);
    }
    
    public AdminEmployeeRemoval(AdminHomePage a) {

        initComponents();
        fillComboBox();
        page = a;
    }
    
    public AdminEmployeeRemoval(AdminHomePage a, int x, int y) {

        initComponents();
        this.setLocation(x, y);
        this.setResizable(false); // Make the frame not resizable
        fillComboBox();
        page = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminTaskAssignLogo = new javax.swing.JLabel();
        EmployeeNameLabel = new javax.swing.JLabel();
        EmployeeListCombo = new javax.swing.JComboBox<>();
        RemoveEmployeeButton = new javax.swing.JButton();
        EmployeeInfoPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        nameValue = new javax.swing.JLabel();
        idValue = new javax.swing.JLabel();
        usernameValue = new javax.swing.JLabel();
        salaryValue = new javax.swing.JLabel();
        positionValue = new javax.swing.JLabel();
        FileError = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        AdminTaskAssignLogo.setBackground(new java.awt.Color(203, 78, 22));
        AdminTaskAssignLogo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        AdminTaskAssignLogo.setForeground(new java.awt.Color(228, 228, 228));
        AdminTaskAssignLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee-removal-label.png"))); // NOI18N

        EmployeeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmployeeNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeNameLabel.setText("Select Employee Username:");

        EmployeeListCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmployeeListCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EmployeeListCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeListComboActionPerformed(evt);
            }
        });

        RemoveEmployeeButton.setBackground(new java.awt.Color(102, 102, 102));
        RemoveEmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RemoveEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveEmployeeButton.setText("Remove Employee");
        RemoveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeButtonActionPerformed(evt);
            }
        });

        EmployeeInfoPanel.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeInfoPanel.setForeground(new java.awt.Color(51, 51, 51));

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        idLabel.setForeground(new java.awt.Color(39, 39, 39));
        idLabel.setText("ID:");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(39, 39, 39));
        nameLabel.setText("Name:");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(39, 39, 39));
        usernameLabel.setText("Username:");

        positionLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(39, 39, 39));
        positionLabel.setText("Position:");

        salaryLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(39, 39, 39));
        salaryLabel.setText("Salary:");

        nameValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        nameValue.setForeground(new java.awt.Color(23, 23, 23));
        nameValue.setText("null");

        idValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        idValue.setForeground(new java.awt.Color(23, 23, 23));
        idValue.setText("null");

        usernameValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        usernameValue.setForeground(new java.awt.Color(23, 23, 23));
        usernameValue.setText("null");

        salaryValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        salaryValue.setForeground(new java.awt.Color(23, 23, 23));
        salaryValue.setText("null");

        positionValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        positionValue.setForeground(new java.awt.Color(23, 23, 23));
        positionValue.setText("null");

        javax.swing.GroupLayout EmployeeInfoPanelLayout = new javax.swing.GroupLayout(EmployeeInfoPanel);
        EmployeeInfoPanel.setLayout(EmployeeInfoPanelLayout);
        EmployeeInfoPanelLayout.setHorizontalGroup(
            EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeInfoPanelLayout.createSequentialGroup()
                        .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel)
                            .addComponent(salaryLabel))
                        .addGap(188, 188, 188)
                        .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salaryValue)
                            .addComponent(positionValue)))
                    .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(EmployeeInfoPanelLayout.createSequentialGroup()
                            .addComponent(usernameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameValue))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmployeeInfoPanelLayout.createSequentialGroup()
                            .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLabel)
                                .addComponent(idLabel))
                            .addGap(211, 211, 211)
                            .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idValue)
                                .addComponent(nameValue)))))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        EmployeeInfoPanelLayout.setVerticalGroup(
            EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeInfoPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValue))
                .addGap(29, 29, 29)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameValue))
                .addGap(34, 34, 34)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(salaryValue))
                .addGap(37, 37, 37)
                .addGroup(EmployeeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(positionValue))
                .addGap(41, 41, 41))
        );

        //EmployeeInfoPanel.setVisible(false);

        FileError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        FileError.setForeground(new java.awt.Color(255, 51, 5));
        FileError.setText("Error Reading File");
        FileError.setVisible(false);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.png"))); // NOI18N
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EmployeeNameLabel)
                        .addGap(121, 121, 121)
                        .addComponent(EmployeeListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminTaskAssignLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FileError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoveEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AdminTaskAssignLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNameLabel))
                .addGap(36, 36, 36)
                .addComponent(EmployeeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileError))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void fillComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        UsernameLedger ledger = new UsernameLedger();

        try {
            for (String username : ledger.getUsernames()) {
                model.addElement(username);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            FileError.setVisible(true);
        }

        EmployeeListCombo.setModel(model);

    }

    private void RemoveEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeButtonActionPerformed

        //UsernameLedger ledger = new UsernameLedger();
        EmployeeSaving fileSave = null;

        try {
            // Ensure that employee is not null before proceeding
            if (employee == null) {
                throw new UserNotFoundException("Employee not initialized");
            }

            UsernameLedger ledger = new UsernameLedger();
            fileSave = new EmployeeSaving(employee);
        } catch (Exception e) {
            RemoveEmployeeButton.setBackground(new java.awt.Color(206, 35, 35));
            RemoveEmployeeButton.setText("Select an employee");
            return;
        }
        try {
            // Ensure that employee is not null before checking the position
            if (employee.getPosition().isBlank()) {
                throw new UserNotFoundException("Employee not initialized");
            } else if (employee.getPosition().contains("Fired")) {
                RemoveEmployeeButton.setBackground(new java.awt.Color(206, 35, 35));
                RemoveEmployeeButton.setText("Employee Already Removed");
            } else {
                fileSave.deleteInfo((String) EmployeeListCombo.getSelectedItem());
                RemoveEmployeeButton.setBackground(new java.awt.Color(0, 128, 0)); // Green to indicate success
                RemoveEmployeeButton.setText("Employee Removed");
            }
        } catch (UserNotFoundException ex) {
            FileError.setVisible(true);
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_RemoveEmployeeButtonActionPerformed

    private void viewEmployeeInfo(String username) {
        try {

            employee = infoReader.readUser(username, false);

            this.nameValue.setText(employee.getName());
            this.idValue.setText(String.valueOf(employee.getId()));
            this.usernameValue.setText(employee.getUsername());
            this.salaryValue.setText(String.valueOf(employee.getSalary()));
            this.positionValue.setText(employee.getPosition());

            FileError.setVisible(false);
            EmployeeInfoPanel.setPreferredSize(new Dimension(792, 349));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            FileError.setVisible(true);
            EmployeeInfoPanel.setPreferredSize(new Dimension(792, 349));
        }
    }

    private void EmployeeListComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeListComboActionPerformed
        String selectedUser = (String) EmployeeListCombo.getSelectedItem();
        viewEmployeeInfo(selectedUser);
    }//GEN-LAST:event_EmployeeListComboActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        page.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRemoval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEmployeeRemoval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminTaskAssignLogo;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel EmployeeInfoPanel;
    private javax.swing.JComboBox<String> EmployeeListCombo;
    private javax.swing.JLabel EmployeeNameLabel;
    private javax.swing.JLabel FileError;
    private javax.swing.JButton RemoveEmployeeButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel positionValue;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel salaryValue;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameValue;
    // End of variables declaration//GEN-END:variables
}
