/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import employeemanager.Employee;
import employeemanager.FileInfoReader;
import java.awt.Dimension;
import java.io.IOException;

/**
 *
 * @author Ralty
 */
public class EmployeeHomePage extends javax.swing.JFrame {

    private String username;
    private boolean toggle = true;
    FileInfoReader infoReader = new FileInfoReader();
    Employee employee;
    
    public EmployeeHomePage() {
        initComponents();
        System.out.println(this.getSize());
    }
    
    public EmployeeHomePage(String username) throws IOException {
        initComponents();
        employee = infoReader.readUser(username, false);
        viewEmployeeInfo(username);
        
        System.out.println(this.getSize());
    }
    
    public EmployeeHomePage(String username, int x, int y) throws IOException {
        initComponents();
        employee = infoReader.readUser(username, false);
        viewEmployeeInfo(username);
        this.setLocation(x, y);
        this.setResizable(false); // Make the frame not resizable
        
        System.out.println(this.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeHomePanel = new javax.swing.JPanel();
        EmployeeHomeInfoPanel = new javax.swing.JPanel();
        ProfileLogo = new javax.swing.JLabel();
        AccountTypeLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        accountValue = new javax.swing.JLabel();
        positionValue = new javax.swing.JLabel();
        salaryValue = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        nameValue = new javax.swing.JLabel();
        idValue = new javax.swing.JLabel();
        usernameValue = new javax.swing.JLabel();
        ageValue = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderValue = new javax.swing.JLabel();
        HomeLogo = new javax.swing.JLabel();
        EmployeeMenuPanel = new javax.swing.JPanel();
        EmployeeViewTaskButton = new javax.swing.JButton();
        PayCalculatorButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        AdminSignOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeHomePanel.setBackground(new java.awt.Color(51, 51, 51));

        EmployeeHomeInfoPanel.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeHomeInfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        ProfileLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-pic1.png"))); // NOI18N

        AccountTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        AccountTypeLabel.setForeground(new java.awt.Color(39, 39, 39));
        AccountTypeLabel.setText("User Type:");

        positionLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(39, 39, 39));
        positionLabel.setText("Position:");

        salaryLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(39, 39, 39));
        salaryLabel.setText("Salary:");

        accountValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        accountValue.setForeground(new java.awt.Color(23, 23, 23));
        accountValue.setText("Employee");

        positionValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        positionValue.setForeground(new java.awt.Color(23, 23, 23));
        positionValue.setText("null");

        salaryValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        salaryValue.setForeground(new java.awt.Color(23, 23, 23));
        salaryValue.setText("null");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(39, 39, 39));
        usernameLabel.setText("Username:");

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        idLabel.setForeground(new java.awt.Color(39, 39, 39));
        idLabel.setText("ID:");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(39, 39, 39));
        nameLabel.setText("Name:");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(39, 39, 39));
        ageLabel.setText("Age:");

        nameValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        nameValue.setForeground(new java.awt.Color(23, 23, 23));
        nameValue.setText("null");

        idValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        idValue.setForeground(new java.awt.Color(23, 23, 23));
        idValue.setText("null");

        usernameValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        usernameValue.setForeground(new java.awt.Color(23, 23, 23));
        usernameValue.setText("null");

        ageValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ageValue.setForeground(new java.awt.Color(23, 23, 23));
        ageValue.setText("null");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(39, 39, 39));
        genderLabel.setText("Gender:");

        genderValue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        genderValue.setForeground(new java.awt.Color(23, 23, 23));
        genderValue.setText("null");

        javax.swing.GroupLayout EmployeeHomeInfoPanelLayout = new javax.swing.GroupLayout(EmployeeHomeInfoPanel);
        EmployeeHomeInfoPanel.setLayout(EmployeeHomeInfoPanelLayout);
        EmployeeHomeInfoPanelLayout.setHorizontalGroup(
            EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ProfileLogo)
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountTypeLabel)
                            .addComponent(positionLabel)
                            .addComponent(salaryLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryValue)
                            .addComponent(positionValue)
                            .addComponent(accountValue)))
                    .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel)
                            .addComponent(nameLabel)
                            .addComponent(idLabel)
                            .addComponent(usernameLabel)
                            .addComponent(genderLabel))
                        .addGap(28, 28, 28)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageValue)
                            .addComponent(usernameValue)
                            .addComponent(idValue)
                            .addComponent(nameValue)
                            .addComponent(genderValue))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        EmployeeHomeInfoPanelLayout.setVerticalGroup(
            EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ProfileLogo))
                    .addGroup(EmployeeHomeInfoPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountTypeLabel)
                            .addComponent(accountValue))
                        .addGap(35, 35, 35)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionLabel)
                            .addComponent(positionValue))
                        .addGap(37, 37, 37)
                        .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryLabel)
                            .addComponent(salaryValue))))
                .addGap(26, 26, 26)
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValue))
                .addGap(35, 35, 35)
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValue))
                .addGap(35, 35, 35)
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameValue))
                .addGap(37, 37, 37)
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageValue))
                .addGap(35, 35, 35)
                .addGroup(EmployeeHomeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderValue))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        HomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homepage-logo.png"))); // NOI18N

        EmployeeMenuPanel.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeMenuPanel.setVisible(false);

        EmployeeViewTaskButton.setBackground(new java.awt.Color(51, 51, 51));
        EmployeeViewTaskButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmployeeViewTaskButton.setForeground(new java.awt.Color(204, 204, 204));
        EmployeeViewTaskButton.setText("View Tasks");
        EmployeeViewTaskButton.setBorderPainted(false);
        EmployeeViewTaskButton.setFocusPainted(false);
        EmployeeViewTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeViewTaskButtonActionPerformed(evt);
            }
        });

        PayCalculatorButton.setBackground(new java.awt.Color(51, 51, 51));
        PayCalculatorButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PayCalculatorButton.setForeground(new java.awt.Color(204, 204, 204));
        PayCalculatorButton.setText("Pay Calculator");
        PayCalculatorButton.setBorderPainted(false);
        PayCalculatorButton.setFocusPainted(false);
        PayCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayCalculatorButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Change Password");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);

        javax.swing.GroupLayout EmployeeMenuPanelLayout = new javax.swing.GroupLayout(EmployeeMenuPanel);
        EmployeeMenuPanel.setLayout(EmployeeMenuPanelLayout);
        EmployeeMenuPanelLayout.setHorizontalGroup(
            EmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                .addGroup(EmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(EmployeeViewTaskButton))
                    .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(PayCalculatorButton))
                    .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        EmployeeMenuPanelLayout.setVerticalGroup(
            EmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(EmployeeViewTaskButton)
                .addGap(62, 62, 62)
                .addComponent(PayCalculatorButton)
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-button.png"))); // NOI18N
        MenuButton.setToolTipText("");
        MenuButton.setBorderPainted(false);
        MenuButton.setContentAreaFilled(false);
        MenuButton.setFocusPainted(false);
        MenuButton.setRolloverEnabled(false);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        AdminSignOut.setBackground(new java.awt.Color(122, 122, 0));
        AdminSignOut.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        AdminSignOut.setForeground(new java.awt.Color(0, 0, 0));
        AdminSignOut.setText("Sign Out");
        AdminSignOut.setBorderPainted(false);
        AdminSignOut.setFocusPainted(false);
        AdminSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeHomePanelLayout = new javax.swing.GroupLayout(EmployeeHomePanel);
        EmployeeHomePanel.setLayout(EmployeeHomePanelLayout);
        EmployeeHomePanelLayout.setHorizontalGroup(
            EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeLogo)
                .addGap(355, 355, 355))
            .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(EmployeeHomeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(MenuButton))
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(EmployeeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(AdminSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        EmployeeHomePanelLayout.setVerticalGroup(
            EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeHomePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HomeLogo)
                .addGap(18, 18, 18)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addComponent(MenuButton)
                        .addGap(18, 18, 18)
                        .addComponent(EmployeeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addComponent(EmployeeHomeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
       
        EmployeeMenuPanel.setVisible(toggle); //Toggles the employee menu button
        toggle = !toggle;
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void EmployeeViewTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeViewTaskButtonActionPerformed
        EmployeeTaskView view = new EmployeeTaskView(employee.getUsername(), this, this.getX(), this.getY());
        this.setVisible(false);
        view.setVisible(true);
    }//GEN-LAST:event_EmployeeViewTaskButtonActionPerformed

    private void PayCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayCalculatorButtonActionPerformed
        EmployeePayCalculator calc = new EmployeePayCalculator(employee.getSalary(), this, this.getX(), this.getY());
        this.setVisible(false);
        calc.setVisible(true);

    }//GEN-LAST:event_PayCalculatorButtonActionPerformed

    private void AdminSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSignOutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_AdminSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeHomePage().setVisible(true);
            }
        });
    }
    
    public void viewEmployeeInfo(String username){
        try{            
            this.nameValue.setText(employee.getName());
            this.idValue.setText(String.valueOf(employee.getId()));
            this.usernameValue.setText(employee.getUsername());
            this.ageValue.setText(String.valueOf(employee.getAge()));
            this.salaryValue.setText(String.valueOf(employee.getSalary()));
            this.positionValue.setText(employee.getPosition());
            
            String gender = (employee.getGender() == 0) ? "Male" : "Female";
            this.genderValue.setText(gender);
            
            //jPanel3.setPreferredSize(new Dimension(824, 451));
            //FileError.setVisible(false);
            

            
        }
        catch (Exception e){
            System.out.println(e.getMessage());
            //FileError.setVisible(true);
            //jPanel3.setPreferredSize(new Dimension(824, 451));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JButton AdminSignOut;
    private javax.swing.JPanel EmployeeHomeInfoPanel;
    private javax.swing.JPanel EmployeeHomePanel;
    private javax.swing.JPanel EmployeeMenuPanel;
    private javax.swing.JButton EmployeeViewTaskButton;
    private javax.swing.JLabel HomeLogo;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton PayCalculatorButton;
    private javax.swing.JLabel ProfileLogo;
    private javax.swing.JLabel accountValue;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageValue;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderValue;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValue;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel positionValue;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel salaryValue;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameValue;
    // End of variables declaration//GEN-END:variables
}
