/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import employeemanager.Admin;
import employeemanager.EmployeeSaving;
import employeemanager.UserNotFoundException;
import employeemanager.UsernameLedger;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ralty
 */
public class Login extends javax.swing.JFrame {

    private String username;
    private String password;
    private SplashScreen splashScreen;
    Admin a1 = new Admin();

    public Login() {
        initComponents();
    }

    //constructor overloading for recieveing SplashScreen.java instance
    public Login(SplashScreen splashScreen) {
        initComponents();
        this.splashScreen = splashScreen; //store the reference to SplashScreen
        setLocationRelativeTo(null); // Set start position to center of the screen
        this.setResizable(false); // Make the frame not resizable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginUserField = new javax.swing.JTextField();
        LoginUserLabel = new javax.swing.JLabel();
        LoginPassField = new javax.swing.JTextField();
        LoginPassLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LoginMenuLabel = new javax.swing.JLabel();
        LoginError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginPanel.setBackground(new java.awt.Color(51, 51, 51));

        LoginUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUserFieldActionPerformed(evt);
            }
        });

        LoginUserLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginUserLabel.setText("Username:");

        LoginPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPassFieldActionPerformed(evt);
            }
        });
        LoginPassField.addActionListener(new java.awt.event.ActionListener() { //for recieving enter key input
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPassFieldActionPerformed(evt);
            }
        });

        LoginPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    LoginButtonActionPerformed(new java.awt.event.ActionEvent(this, java.awt.event.ActionEvent.ACTION_PERFORMED, ""));
                }
            }
        });

        LoginPassLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginPassLabel.setText("Password:");

        LoginButton.setBackground(new java.awt.Color(51, 51, 51));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginMenuLabel.setBackground(new java.awt.Color(51, 51, 51));
        LoginMenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 38));
        LoginMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginMenuLabel.setText("Login Menu");

        LoginError.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LoginError.setForeground(new java.awt.Color(255, 51, 51));
        LoginError.setText("Wrong credentials!");
        LoginError.setVisible(false);

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(LoginUserLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(LoginPassLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LoginError)
                                    .addComponent(LoginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(319, 319, 319))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(LoginMenuLabel)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(437, 437, 437))))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(LoginMenuLabel)
                .addGap(112, 112, 112)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUserLabel))
                .addGap(54, 54, 54)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginPassLabel))
                .addGap(39, 39, 39)
                .addComponent(LoginError)
                .addGap(30, 30, 30)
                .addComponent(LoginButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPassFieldActionPerformed


    }//GEN-LAST:event_LoginPassFieldActionPerformed

    private void LoginUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUserFieldActionPerformed

    }//GEN-LAST:event_LoginUserFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        username = LoginUserField.getText();
        password = LoginPassField.getText();

        if (username.equals(a1.getUsername()) && password.equals(a1.getPassword())) { //for admin login
            this.splashScreen.setVisible(false);
            this.setVisible(false);
            splashScreen.setVisible(false);
            AdminHomePage a = new AdminHomePage(username, this.getX(), this.getY());
            a.setVisible(true);
            return;
        }

        EmployeeSaving save = new EmployeeSaving();
        try {
            if (save.checkFired(username)) {
                LoginError.setVisible(true);
                LoginError.setText("Employee Fired");
                return;
            }

        } catch (UserNotFoundException ex) {
            LoginError.setVisible(true);
            LoginError.setText("File Error");
            System.out.println(ex.getMessage());;
        }

        UsernameLedger ledger = new UsernameLedger();
        System.out.println(username);
        try {
            if (ledger.usernameSearch(username)) {
                String path = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "EmployeeManager";
                String fileName = ((username) + ".txt");
                File f1 = new File(path, fileName);
                BufferedReader reader = new BufferedReader(new FileReader(f1));
                String line;
                while ((line = reader.readLine()) != null) {
                    //check if the line contains "Assigned Tasks:"
                    if (line.contains("Password")) {
                        //extract the current value of password and check it
                        String pass = (line.split(":")[1].trim());
                        
                        if(this.password.equals(pass)){
                            EmployeeHomePage e = new EmployeeHomePage(this.username, this.getX(), this.getY());
                            this.setVisible(false);
                            splashScreen.setVisible(false);
                            e.setVisible(true);
                            return;
                        }
                    }

                }
                reader.close();
            }
        } catch (UserNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LoginError.setVisible(true);

    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public javax.swing.JPanel getLoginPanel() {
        return LoginPanel;
    }

    private void attemptLogin() {
        username = LoginUserField.getText();
        password = LoginPassField.getText();

        if (username.equals(a1.getUsername()) && password.equals(a1.getPassword())) {
            this.splashScreen.setVisible(false);
            this.setVisible(false);
            this.repaint();
            AdminHomePage a = new AdminHomePage();
            a.setVisible(true);
        } else {
            LoginError.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginError;
    private javax.swing.JLabel LoginMenuLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JTextField LoginPassField;
    private javax.swing.JLabel LoginPassLabel;
    private javax.swing.JTextField LoginUserField;
    private javax.swing.JLabel LoginUserLabel;
    // End of variables declaration//GEN-END:variables
}
